version: '3'

services:

  # Start Postgres
  postgres:
    image: 'postgres:13.4'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fenix
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  # Start Redis
  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./db-data/redis/:/data

  # Start MariaDB
  mariadb:
    image: 'mariadb:10.6'
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_USER: mariadb
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: fenix

    volumes:
      - ./db-data/mariadb:/docker-entrypoint-initdb.d